var faqQuestions = [
    'What has FirstBlood been doing for the past few years?',
    'How did FirstBlood use the money that was raised during the ICO in 2016?',
    'I thought you were focused on blockchain technology; does FirstBlood have any plans to launch a token?',
    'If Ethereum’s ability to scale was inhibiting FirstBlood’s development, why didn’t the project migrate to a faster chain?',
    'What is Dawn?',
    'Why launch a new blockchain?',
    'What benefits will the Cosmos network bring to users?',
    'What’s happening to the 1st token?',
    'What are Dawn tokens and what are they used for?',
    'Which blockchain protocol will Dawn employ?',
    'Will players be able to wager using Dawn token?'
]
var faqAnswers = [
    'In 2016, FirstBlood raised $5.5 million in an Initial Coin Offering (ICO). We have since seen our token rise to highs of nearly three dollars, and lows of nearly two cents.  We have focused on quietly building the infrastructure for our product in a way that is useful for the community that has funded us. We developed the first Decentralized Application (Dapp) for PC, with DOTA2, and have also worked to resolve the issues and limited capabilities facing mobile users, focusing on building user traction.<br>Now, with the launch of our 2.0 Tendermint-Based Blockchain, we have solved the user-friction problem in esports wagering, and we believe the gaming world/market is ready for it.',
    'Since launching our ICO in 2016 - which was one of the first launched on Ethereum - FirstBlood has focused on quietly building infrastructure rather than a market for an asset that our users weren’t ready for. To that end, we put our heads down and developed a hugely popular mobile app, which we launched on the Google Play Store in October. The app has been really popular with users, with numbers of daily active users growing at a rate of between 6 - 8k and total users recently topping 100,000.',
    'Since its foundation, FirstBlood’s aim has always been to use decentralized technologies, such as blockchain, to solve problems that exist within the esports community. Our mission was to create a decentralized platform for gamers to meet and compete, and that hasn’t changed. However, Ethereum’s inability to scale to meet the needs of a growing number of users caused substantial friction, which taught us what many others in the crypto space have come to realize; the value proposition of decentralization alone is not enough to build a successful platform. That said, blockchain technology remains a core part of our future plans, and we will have more information to share on this in the coming weeks.',
    'Like many Ethereum-based projects, we believed in the core team’s ability to build a scaling solution, and we believe in their ability to this day. However, by the end of 2018, Ethereum’s hash rate had risen by 10,000% from the rate at our ICO, meaning it would not be viable for our model to operate until Ethereum releases its long-awaited 2.0 scaling solutions. Waiting for that solution, though,  was not an option for us, and so we began the search for a scalable solution that would allow us to finally build the killer dApp.',
    'Dawn is our new blockchain that we are building as a “Cosmos Zone” built on Tendermint consensus, using a bridge contract deployed on the Ethereum mainnet. Building Dawn this way means that ERC-20 tokens can be safely moved into, and later withdrawn from, the Dawn Chain.',
    'Firstblood’s Tendermint-based blockchain, Dawn, is currently being built using Cosmos SDK. It solves several of the problems that our previous chain, FirstBloodChain, was facing, and allows us to deliver a truly decentralized, and friction-minimized platform for esports wagering.<br>The Tendermint architecture allows FirstBlood to scale transactions per second well above the current Ethereum limit, and at significantly less cost to end users, while keeping Ethereum as our top layer. This means that we can eliminate the scaling problems we encountered in building on Ethereum without losing its credibility as a powerful, trusted platform for maintaining token ownership and transactions.',
    'The Cosmos network will bring a variety of benefits to users, including:<ul><li>Lower transaction fees </li><li>Security of tokens</li><li>Frictionless user experience</li><li>Chance to deposit stablecoins and other assets, and take advantage of a higher TPS rate</li></ul>In addition to the above, applications built on Cosmos can take advantage of built-in interoperability, meaning that they can communicate with one another. This has myriad advantages for users who want to make use of services across multiple blockchains and avail of fast transaction times while still utilizing decentralized applications.',
    'The ERC-20 tokens can be safely moved into, or withdrawn from, the Dawn chain. This is enabled due to a bridge contract deployed on the Ethereum mainnet, connected to the “Cosmos Zone” on the Tendermint consensus that the Dawn Chain is built upon.',
    'The new Dawn token will act as a staking and governance token. An inflationary mechanism will be implemented to encourage 1ST holders to stake their new Dawn tokens and protect the network. To properly ensure this outcome, the inflation rate of the Dawn token will start relatively high to encourage 1ST token holders to quickly migrate to the new blockchain and stake their tokens.',
    'Dawn is built using the Cosmos SDK and Tendermint Core consensus mechanism, a Byzantine fault tolerant (BFT) consensus engine that prioritizes security and scalability. Tendermint works even if up to ⅓ of machines on the network fail in arbitrary ways, making it extremely stable. It is also the same consensus mechanism as used by the Cosmos Network.',
    'The new Dawn token will act only as a staking and governance token, not as a chip to be wagered.  Instead, users will be able to enter our “Cosmos Zone” to wager stablecoins and other cryptoassets, with a percentage of the fees collected floating up to FirstBlood token-holders via smart contracts.<br>This will exponentially strengthen the value proposition of our underlying token that will ultimately allow holders to control the platform itself.'
]